backend              = "xrender";
use-damage           = true;
full-damage          = true;
unredir-if-possible  = true;
shadow               = false;
fading               = true;
fade-in-step         = 0.04;
fade-out-step        = 0.04;
static-blur          = true;
