# --- Basic Tmux Configuration ---

# Plugins

set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'tmux-plugins/tmux-yank'


# Remap prefix to 'Alt + a'
unbind C-b
unbind M-\;
set-option -g prefix M-a
bind-key M-a send-prefix

# tmux-yank config
set-window-option -g mode-keys vi

bind-key -T copy-mode-vi v send-keys -X begin-selection
bind-key -T copy-mode-vi C-v send-keys -X rectangle-toggle
bind-key -T copy-mode-vi y send-keys -X copy-selection-and-cancel

# Enable mouse support
set -g mouse on

# Reload config file with 'Prefix + r'
bind r source-file ~/.tmux.conf \; display "Config reloaded!"

# Split panes WITHOUT prefix
# Alt + n for Horizontal split (top/bottom)
# Alt + m for Vertical split (left/right)
bind-key -n M-n split-window -v -c "#{pane_current_path}"
bind-key -n M-m split-window -h -c "#{pane_current_path}"

# Window (Tab) Management WITHOUT prefix
# Ctrl + t for New Window
# Ctrl + w for Close Window (Warning: Overrides shell delete-word)
# Ctrl + Tab to cycle windows
# Ctrl + Shift + Tab to reverse cycle
bind-key -n C-t new-window
bind-key w kill-window
bind-key -n C-e next-window
bind-key -n C-S-e previous-window

# Switch panes using vi keys (Prefix + h, j, k, l)
bind h select-pane -L
bind j select-pane -D
bind k select-pane -U
bind l select-pane -R

# Start window and pane numbering at 1
set -g base-index 1
setw -g pane-base-index 1

# Don't rename windows automatically
set-option -g allow-rename off

# Improve colors
set -g default-terminal "screen-256color"
set-option -sa terminal-overrides ",xterm*:Tc"

# Status bar styling
set -g status-bg black
set -g status-fg white

run '~/.tmux/plugins/tpm/tpm'
