vo=gpu
gpu-api=opengl

hwdec=mediacodec

# Interface
osd-bar=yes
osd-font-size=32
osd-on-seek=bar

# Subtitles
sub-auto=fuzzy
sub-file-paths=subs:subtitles
blend-subtitles=yes

# Audio
volume=100
volume-max=150

# Screenshots
screenshot-format=png
screenshot-png-compression=8
screenshot-directory=~/Pictures/mpv-screenshots

# Cache
cache=yes
demuxer-max-bytes=100M
demuxer-max-back-bytes=30M

# vim: ft=sh
