#!/data/data/com.termux/files/usr/bin/bash

display(){
  bspc monitor -d 1 2 3 4 5
  xsetroot -cursor_name left_ptr
}

gaps(){
  bspc config window_gap 10
  bspc config top_padding 50
  bspc config bottom_padding 10
  bspc config right_padding 100
  bspc config left_padding 100
}

clients(){
  bspc rule -a "Xfce4-taskmanager" state=floating layer=above
  bspc rule -a "firefox-default" desktop='^2'
  bspc rule -a scratchpad state=floating
  bspc config pointer_follows_focus false
  bspc config focus_follows_pointer true
  bspc config border_width 2
  bspc config normal_border_color '#322d28'
  bspc config active_border_color '#c09d59'
  bspc config focused_border_color '#c09d59'
}

compositor(){
  killall fastcompmgr
  sleep 1
  fastcompmgr \
    -r 10 \
    -t -15 \
    -l -15 \
    -o 0.7 \
    -m 1 \
    -c \
    -C \
    -i 1 \
    --corner-radius 0 \
    --blur-sigma 20 \
    --border-width 0 
    # --border-color '#c09d59' \
    # --inactive-border-color '#322d28' \
}

autostart(){
  kill -9 $(pgrep -x "sxhkd") > /dev/null 
  sxhkd -c ~/.config/bspwm/sxhkdrc &
  feh --bg-fill /sdcard/Pictures/gowall/138841147_p0.png &
  kill -9 $(pgrep -x "eww") > /dev/null
  eww open bar &
}

__main__(){
  display
  gaps
  clients
  compositor &
  autostart
}
__main__
